! edge-br - enterprise lab
frr version 9.1
frr defaults traditional
hostname edge-br
service integrated-vtysh-config
!
ip forwarding
!
interface lo
 ip address 10.255.0.4/32
!
interface eth1
 description to core1
 ip address 10.0.0.14/30
!
interface eth2
 description to core2
 ip address 10.0.0.18/30
!
interface eth3
 description VLAN 20 - branch users
 ip address 10.20.20.1/24
!
router ospf
 ospf router-id 10.255.0.4
 network 10.0.0.12/30 area 0
 network 10.0.0.16/30 area 0
 network 10.20.20.0/24 area 0
 network 10.255.0.4/32 area 0
!
line vty
!
