! edge-hq - enterprise lab
frr version 9.1
frr defaults traditional
hostname edge-hq
service integrated-vtysh-config
!
ip forwarding
!
interface lo
 ip address 10.255.0.3/32
!
interface eth1
 description to core1
 ip address 10.0.0.6/30
!
interface eth2
 description to core2
 ip address 10.0.0.10/30
!
interface eth3
 description VLAN 10 - HQ users
 ip address 10.10.10.1/24
!
interface eth4
 description VLAN 99 - management
 ip address 10.10.99.1/24
!
router ospf
 ospf router-id 10.255.0.3
 network 10.0.0.4/30 area 0
 network 10.0.0.8/30 area 0
 network 10.10.10.0/24 area 0
 network 10.10.99.0/24 area 0
 network 10.255.0.3/32 area 0
!
line vty
!
