---
all:
  vars:
    ansible_connection: community.docker.docker
    ansible_user: root

    segment_client: 10.0.1.0/24
    segment_server: 10.0.2.0/24
    segment_mgmt: 10.0.99.0/24
    segment_transit: 10.0.12.0/30
    client_ip: 10.0.1.10
    server_ip: 10.0.2.10
    mgmt_ip: 10.0.99.10

  children:
    routers:
      hosts:
        r1:
          ansible_host: clab-thesis-net-r1
        r2:
          ansible_host: clab-thesis-net-r2

    lab_hosts:
      hosts:
        h-client:
          ansible_host: clab-thesis-net-h-client
        h-server:
          ansible_host: clab-thesis-net-h-server
        h-mgmt:
          ansible_host: clab-thesis-net-h-mgmt